# Generated by Django 4.2 on 2025-01-01 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_alter_deposit_options_alter_deposit_account_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deposit",
            old_name="currency",
            new_name="crypto_currency",
        ),
    ]
